### ISSUE TITLE
Multi-machine training, embeddings cannot be loaded during the second epoch.

### ISSUE THREAD

**Issue by ZenoTan** [facebookresearch/PyTorch-BigGraph#117]
## Steps to reproduce

  1. Set up 4 machines and 8 partitions, using tcp as communication method.
  2. Run training script for fb15k on each machine.
  3. Train successfully for an epoch, but during the second one, an error will occur.

## Observed Results

  * Log (rank 0-3 are similar)
2019-12-04 04:16:18,398   [Trainer-1] still in queue: 0
2019-12-04 04:16:18,398   [Trainer-1] Swapping partitioned embeddings ( 4 , 3 ) None
2019-12-04 04:16:18,398   [Trainer-1] Writing partitioned embeddings
2019-12-04 04:16:19,420   [Trainer-1] Swapping partitioned embeddings None None
2019-12-04 04:16:20,303   [Trainer-1] Finished epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2019-12-04 04:16:20,304   [Trainer-1] Writing the checkpoint
2019-12-04 04:16:20,333   [Trainer-1] Waiting for other workers to write their parts of the checkpoint
2019-12-04 04:16:20,406   [Trainer-1] All parts of the checkpoint have been written
2019-12-04 04:16:20,406   [Trainer-1] Switching to the new checkpoint version
2019-12-04 04:16:20,406   [Trainer-1] Waiting for other workers to switch to the new checkpoint version
2019-12-04 04:16:20,410   [Trainer-1] All workers have switched to the new checkpoint version
2019-12-04 04:16:20,410   [Trainer-1] Starting epoch 2 / 50, edge path 1 / 1, edge chunk 1 / 1
2019-12-04 04:16:20,410   [Trainer-1] Edge path: data/FB15k/freebase_mtr100_mte100-train_partitioned
2019-12-04 04:16:20,412   [Trainer-1] Lock client new epoch...
2019-12-04 04:16:20,421   [Trainer-1] still in queue: 62
2019-12-04 04:16:20,421   [Trainer-1] Swapping partitioned embeddings None ( 2 , 2 )
2019-12-04 04:16:20,421   [Trainer-1] ( 2 , 2 ): Loading entities
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/checkpoint_storage.py", line 354, in load_entity_partition
    with h5py.File(path, "r") as hf:
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/ubuntu/PyTorch-BigGraph/model/fb15k/embeddings_all_1.v1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/bin/torchbiggraph_train", line 11, in <module>
2019-12-04 04:16:20,428  [LockServer] Bucket ( 3 , 3 ) acquired by trainer 2: active= {Bucket(lhs=0, rhs=0): 3, Bucket(lhs=1, rhs=1): 0, Bucket(lhs=2, rhs=2): 1, Bucket(lhs=3, rhs=3): 2}
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/train.py", line 967, in main
    train(config, rank=Rank(opt.rank), subprocess_init=subprocess_init)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/train.py", line 938, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank, subprocess_init):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/train.py", line 701, in train_and_report_stats
    io_bytes += swap_partitioned_embeddings(old_b, cur_b, old_stats)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/train.py", line 632, in swap_partitioned_embeddings
    entity, part, strict=strict, force_dirty=force_dirty)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/train.py", line 499, in load_embeddings
    force_dirty=force_dirty)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/checkpoint_manager.py", line 359, in read
    self.storage.load_entity_partition(version, entity, part)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/checkpoint_storage.py", line 363, in load_entity_partition
    raise CouldNotLoadData() from err
torchbiggraph.util.CouldNotLoadData

  * Files
Embeddings were stored 2 partitions each machine, instead of all entities.

## Expected Results

  * Embeddings should be successfully loaded after the first epoch.

## Relevant Code

  ```
torchbiggraph_train   torchbiggraph/examples/configs/fb15k_config.py   -p edge_paths=data/FB15k/freebase_mtr100_mte100-train_partitioned   --rank 0

config = dict(
        # I/O data
        entity_path="data/FB15k",
        edge_paths=[
            "data/FB15k/freebase_mtr100_mte100-train_partitioned",
            "data/FB15k/freebase_mtr100_mte100-valid_partitioned",
            "data/FB15k/freebase_mtr100_mte100-test_partitioned",
        ],
        checkpoint_path="model/fb15k",

        # Graph structure
        entities={
            'all': {'num_partitions': 8},
        },
        relations=[{
            'name': 'all_edges',
            'lhs': 'all',
            'rhs': 'all',
            'operator': 'translation',
        }],
        dynamic_relations=True,

        # Scoring model
        dimension=400,
        global_emb=False,
        comparator='l2',

        # Training
        num_epochs=50,
        num_uniform_negs=1000,
        loss_fn='softmax',
        lr=0.1,
        num_machines=4,
        distributed_init_method='tcp://172.31.43.194:23456',

        # Evaluation during training
        eval_fraction=0,  # to reproduce results, we need to use all training data
    )
  ```

**Comment by lerks** [comment]
You need to set `checkpoint_path` to a location that is shared by all trainers, for example a NFS mount, so that the files written there by one trainer are visible to all other ones.

**Comment by rinisin13** [comment]
Thanks for explaining the reason behind the error.  I 'm also trying to run training in distributed mode but currently, we don't have any provision for shared NFS mount location. is there any workaround?
