### ISSUE TITLE
Multi-machine training: Runtime error using distributed with gloo

### ISSUE THREAD

**Issue by RweBs** [facebookresearch/PyTorch-BigGraph#119]
## Steps to reproduce

1. Set up 2 machines and 4 partitions, using shared files(NFS) as communication method.
2. Run training script for fb15k on each machine.
3. got a runtime error 

## Observed Results

> torchbiggraph_train   torchbiggraph/examples/configs/fb15k_config.py  --rank 0

**Logs (machine 1/2 are the same but the port number is different)** 
2019-12-09 16:57:53,769   [Trainer-0] Loading entity counts...
2019-12-09 16:57:53,771   [Trainer-0] Setup lock server...
2019-12-09 16:57:53,776   [Trainer-0] Setup param server...
2019-12-09 16:57:53,784   [Trainer-0] init_process_group start
2019-12-09 16:57:54,456    [ParamC-0] init_process_group start
2019-12-09 16:57:54,470     [PartS-0] init_process_group start
2019-12-09 16:57:54,526    [ParamS-0] init_process_group start
2019-12-09 16:57:54,526  [LockServer] init_process_group start
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/parameter_sharing.py", line 395, in _client_thread_loop
    groups=groups,
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 89, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 410, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 478, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:761] connect [::1]:8355: Connection refused
Process ParamC-0:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/parameter_sharing.py", line 395, in _client_thread_loop
    groups=groups,
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 89, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 410, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 478, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:761] connect [::1]:8355: Connection refused
Process PartS-0:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 121, in _server_init
    groups=groups,
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 89, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 410, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 478, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:761] connect [::1]:4241: Connection refused

## Expected Results

- Get final results like running on single-machine.

## Relevant Code

```
def get_torchbiggraph_config():

    config = dict(
        # I/O data
        entity_path="/home/public/FB15k",
        edge_paths=[
            "/home/public/FB15k/freebase_mtr100_mte100-train_partitioned",
            "/home/public/FB15k/freebase_mtr100_mte100-valid_partitioned",
            "/home/public/FB15k/freebase_mtr100_mte100-test_partitioned",
        ],
        checkpoint_path="/home/public/FB15k/model/fb15k-transE",

        # Graph structure
        entities={
            'all': {'num_partitions': 4},
        },
        relations=[{
            'name': 'all_edges',
            'lhs': 'all',
            'rhs': 'all',
            'operator': 'translation',
        }],
        dynamic_relations=True,

        # Scoring model
        dimension=400,
        global_emb=False,
        comparator='l2',

        # Training
        num_epochs=50,
        num_uniform_negs=1000,
        loss_fn='softmax',
        lr=0.1,
        
        num_machines=2,
        distributed_init_method='file:///home/public/share',
        # Evaluation during training
        eval_fraction=0,  # to reproduce results, we need to use all training data
    )

    return config
```

**Comment by lerks** [comment]
I've never seen this error before, but I can make a guess. Is it perhaps that your machines have firewalls set up so that connections between processes on the same machine are blocked? Observe that, even if you use a shared file rendezvous, this is only used at initialization to make the processes aware of each other, but afterwards they still have to open pairwise connections among all of them, and this looks like the step that fails.

From the logs it would seem that it's the processes on the same machine that are having troubles connecting (the IPv6 address is `::1`, which means localhost). To see whether this is a problem with your setup or with PBG you can try running the following commands on the same machine (open two shells either with tmux or by ssh-ing in twice): first launch `nc -6 -l 8355` (8355 is one of the ports I saw in your logs), then launch `nc `-6 ::1 8355` then type something and press enter, finally make sure that what you typed appeared in the first command's output.

If the above doesn't work, then your machines have a weird setup and you'll need to figure out what's going on. If the above works, we'll have to try to get another repro...

**Comment by RweBs** [comment]
Thank you for your reply. It seems that your approach works well (The words I type in one shell appears in another one) , but errors are still here. 

**rank 0 server seems works well:**
```
2019-12-09 18:27:45,861   [Trainer-0] Loading entity counts...
2019-12-09 18:27:45,862   [Trainer-0] Setup lock server...
2019-12-09 18:27:45,868   [Trainer-0] Setup param server...
2019-12-09 18:27:45,878   [Trainer-0] init_process_group start
2019-12-09 18:27:46,493    [ParamC-0] init_process_group start
2019-12-09 18:27:46,518     [PartS-0] init_process_group start
2019-12-09 18:27:46,549    [ParamS-0] init_process_group start
2019-12-09 18:27:46,573  [LockServer] init_process_group start
```

**rank 1 server can not work: (I have tested the 3999 port using the `nc -6 -l 3999` and `nc -6 ::1 3999`)**
```
2019-12-09 18:29:58,423   [Trainer-1] Loading entity counts...
2019-12-09 18:29:58,425   [Trainer-1] Setup param server...
2019-12-09 18:29:58,436   [Trainer-1] init_process_group start
Traceback (most recent call last):
  File "/usr/local/bin/torchbiggraph_train", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/train.py", line 967, in main
    train(config, rank=Rank(opt.rank), subprocess_init=subprocess_init)
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/train.py", line 938, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank, subprocess_init):
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/train.py", line 423, in train_and_report_stats
    groups=[ranks.trainers],
  File "/usr/local/lib/python3.6/site-packages/torchbiggraph/distributed.py", line 89, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 410, in init_process_group
    timeout=timeout)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 478, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:761] connect [::1]:3999: Connection refused
```

The status of firewalld is **inactive** on both two machines.

**Comment by pietern** [comment]
You mention 2 machines, so using `localhost` isn't going to cut it. I expect the error to come from machine A trying to connect to machine B over `localhost`, which obviously won't work.

By default, PyTorch will use the machine's hostname to figure out its external IP address. It is likely that the hostname of the machines you're using both resolve to `::1` instead. To override this behavior, you can set the `GLOO_SOCKET_IFNAME` environment variable to the name of the network interface that connects these machines (for example `GLOO_SOCKET_IFNAME=eth0`).

Can you give this a try and see if it resolves the issue?

**Comment by lerks** [comment]
Just to check of one thing, every time you re-launch the script are you making sure to remove the file used to synchronize (i.e., `/home/public/share`)? See https://pytorch.org/docs/master/distributed.html#shared-file-system-initialization

**Comment by RweBs** [comment]
Thanks for your answers, I modified the `/etc/hosts`, deleted the localhost related content (only the host name and ip address of the clusters was retained), and added `export GLOO_SOCKET_IFNAME = eth0` to the `/etc/profile `file, now It works!

**Comment by pietern** [comment]
@RweBs Glad to hear!

You don't need to do both, by the way. You can keep `/etc/hosts` the same and use `GLOO_SOCKET_IFNAME`, or remove the mapping from the machine's hostname to localhost from `/etc/hosts`. Both should do the trick.

**Comment by lerks** [comment]
Closing this as I understand the issue to have been solved.
