### ISSUE TITLE
Converting the output back to TSV

### ISSUE THREAD

**Issue by dstaehler** [facebookresearch/PyTorch-BigGraph#124]
Hello all,

I'm playing around with the PyTorch BigGraph code and all works pretty well for me except the export back to TSV format.

I suppose in contrast to your GitHub documentation due to the JSON based config file and the information from torchbiggraph_export_to_tsv -h the order of the parameters has to be changed.

usage: torchbiggraph_export_to_tsv [-h] [-p [PARAM [PARAM ...]]]
                                   --entities-output ENTITIES_OUTPUT
                                   --relation-types-output
                                   RELATION_TYPES_OUTPUT
                                   config

I used the simple export setting like this:

torchbiggraph_export_to_tsv --entities-output entity_embeddings.tsv --relation-types-output relation_types_parameters.tsv config.json

while being inside of the activated BigGraph env. 

I get the following error message:

Traceback (most recent call last):
  File "/.../code/biggraph/bin/torchbiggraph_export_to_tsv", line 10, in <module>
    sys.exit(main())
  File "/.../code/biggraph/lib/python3.7/site-packages/torchbiggraph/converters/export_to_tsv.py", line 147, in main
    config = loader.load_config(opt.config, overrides)
  File "/.../code/biggraph/lib/python3.7/site-packages/torchbiggraph/config.py", line 471, in load_config
    config_dict = self.load_raw_config(path)
  File "/.../code/biggraph/lib/python3.7/site-packages/torchbiggraph/config.py", line 462, in load_raw_config
    module = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/folders/21/v3_m4wk95077vd7bnx_91g740000gp/T/torchbiggraph_config_1z2qdkz4/torchbiggraph_config_015c05bf520f433398001e455c78af01.py", line 5, in <module>
    "featurized": false
NameError: name 'false' is not defined

The BigGraph env dir is pretty long that's why I have shortened it with /.../

Any idea how to fix this would be greatly appreciated.

Best regards

**Comment by lerks** [comment]
The config file you're passing as a command-line argument is a JSON file, whereas it should be a Python file, namely the same Python file you used for training.

**Comment by dstaehler** [comment]
Hi, thanks for the quick reply. I think I got confused by the fb15k example because the script didn't produce a config.py. Instead it appears to me it is working on a config.json file. That's the reason why I picked that one for the export. Is this an issue because it is a former version?

**Comment by lerks** [comment]
Indeed, the training program saves a copy of the config inside the checkpoint as a JSON file. But this is just for future reference, for example in case one's running many experiments and needs help remembering what model each directory contains.

If you look in the README, all commands include `torchbiggraph/examples/configs/fb15k_config.py` as a command line argument. That file contains the Python version of the FB15k config (the "source" of the JSON), and it should also be given to the export command.

**Comment by lerks** [comment]
It is true that the export command changed a few times recently, so please make sure you're using the latest version of PBG (either v1.0.0, or master).
