### ISSUE TITLE
RuntimeError: A subprocess exited unexpectedly with status -9

### ISSUE THREAD

**Issue by wintor12** [facebookresearch/PyTorch-BigGraph#134]
I am using this package to train entity embeddings in a KB, I follows the instruction and it works well to prepare the data, train, and even convert the output. However, when I run evaluation, it shows the following error:

```
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/bin/torchbiggraph_eval", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/eval.py", line 254, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/eval.py", line 231, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/eval.py", line 183, in do_eval_and_report_stats
    get_async_result(future_all_bucket_stats, pool)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torchbiggraph/util.py", line 255, in get_async_result
    f"A subprocess exited unexpectedly with status {p.exitcode}")
RuntimeError: A subprocess exited unexpectedly with status -9
```

**Comment by azchrinn** [comment]
I have the exact same issue. Running the data for FB15K works fine, but if i alter the data to my own, but with the exact same formatting in terms of the train, test, val files from the FB15K example, i get the -9 error message on eval.

**Comment by adamlerer** [comment]
I tried reproducing this by following the instructions on the README, but everything worked fine. Could you provide more details? To start, please provide the exact set of commands you ran that led to the error. Thanks!

**Comment by lw** [comment]
Exit code -9 means SIGKILL. I see you're on AWS (your username is `ec2-user`). From Googling a bit it seems that AWS instances may have a OOM killer, i.e., a system that kills other processes when they use too much memory. On FB15k the evaluation is done by comparing to all negatives, which does indeed mean that the intermediate tensors with the scores are larger than during training. This might explain the problem. You could try playing with the batch size to see if that helps.
