### ISSUE TITLE
Failed to train on GPU

### ISSUE THREAD

**Issue by vadimosipov** [facebookresearch/PyTorch-BigGraph#151]
## Steps to reproduce

  torchbiggraph_train fb15k_config_gpu.py  -p edge_paths=data/FB15k/freebase_mtr100_mte100-train_partitioned

## Observed Results

  * What happened?  This could be a description, log output, etc.

GPU:
Driver Version                      : 418.67
CUDA Version                        : 10.1

Command output:
2020-07-13 01:17:33,680   [Trainer-0] Loading entity counts...
2020-07-13 01:17:33,681   [Trainer-0] Creating workers...
2020-07-13 01:17:33,768   [Trainer-0] Initializing global model...
2020-07-13 01:17:33,803   [Trainer-0] Creating GPU workers...
2020-07-13 01:17:33,822   [Trainer-0] Starting epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2020-07-13 01:17:33,823   [Trainer-0] Edge path: data/FB15k/freebase_mtr100_mte100-train_partitioned
2020-07-13 01:17:33,823   [Trainer-0] still in queue: 0
2020-07-13 01:17:33,823   [Trainer-0] Swapping partitioned embeddings None ( 0 , 0 )
2020-07-13 01:17:33,824   [Trainer-0] Loading partitioned embeddings from checkpoint
Process GPU #0:
Traceback (most recent call last):
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torchbiggraph/train_gpu.py", line 159, in run
    torch.cuda.check_error(res)
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torch/cuda/__init__.py", line 189, in check_error
    raise CudaError(res)
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torch/cuda/__init__.py", line 183, in __init__
    msg = _cudart.cudaGetErrorString(code).decode('utf-8')
TypeError: cudaGetErrorString(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch._C._cudart.cudaError) -> str

Invoked with: 1
Traceback (most recent call last):
  File "/home/appuser/.conda/envs/pytorch/bin/torchbiggraph_train", line 8, in <module>
    sys.exit(main())
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torchbiggraph/train.py", line 71, in main
    train(config, rank=opt.rank, subprocess_init=subprocess_init)
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torchbiggraph/train.py", line 42, in train
    coordinator.train()
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torchbiggraph/train_cpu.py", line 659, in train
    stats = self._coordinate_train(edges, eval_edge_idxs, epoch_idx)
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torchbiggraph/train_gpu.py", line 616, in _coordinate_train
    gpu_idx, result = self.gpu_pool.wait_for_next()
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/site-packages/torchbiggraph/train_gpu.py", line 365, in wait_for_next
    res = p.master_endpoint.recv()
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/appuser/.conda/envs/pytorch/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

## Expected Results

  * What did you expect to happen?

I expected to get trained results

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

I've run the command on the master branch, unpack, ran the import stage (it was successful) and then the train one. That's all

**Comment by lw** [comment]
A bug in PyTorch is preventing us from seeing the real error of the CUDA call. I'm fixing that bug in #41330 but until that is merged you could help us debug this by manually adding a `logger.error(f"CUDA error: {res}")` in between these two lines:
https://github.com/facebookresearch/PyTorch-BigGraph/blob/4ca238f7d27a6e720b30587f326dd5a40315cc88/torchbiggraph/train_gpu.py#L158-L159

**Comment by vadimosipov** [comment]
Here you are @lw , 
console output (the stacktrace is the same):
2020-07-13 12:38:23,303   [Trainer-0] Loading entity counts...
2020-07-13 12:38:23,304   [Trainer-0] Creating workers...
2020-07-13 12:38:23,404   [Trainer-0] Initializing global model...
2020-07-13 12:38:23,440   [Trainer-0] Creating GPU workers...
2020-07-13 12:38:23,462   [Trainer-0] Starting epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2020-07-13 12:38:23,463   [Trainer-0] Edge path: data/FB15k/freebase_mtr100_mte100-train_partitioned
2020-07-13 12:38:23,464   [Trainer-0] still in queue: 0
2020-07-13 12:38:23,464   [Trainer-0] Swapping partitioned embeddings None ( 0 , 0 )
2020-07-13 12:38:23,464   [Trainer-0] Loading partitioned embeddings from checkpoint
2020-07-13 12:38:24,811      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7f63cabf3150 at 0x7f6370ed65d0>
2020-07-13 12:38:27,035      [GPU #0] ERROR: CUDA error: 0
2020-07-13 12:38:27,037      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7f63cabf3150 at 0x7f6370eda950>
2020-07-13 12:38:27,038      [GPU #0] ERROR: CUDA error: 0
2020-07-13 12:38:27,038      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7f63cabf3150 at 0x7f6370eda990>
2020-07-13 12:38:27,042      [GPU #0] ERROR: CUDA error: 0
2020-07-13 12:38:27,042      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7f63cabf3150 at 0x7f6370eda9d0>
2020-07-13 12:38:27,043      [GPU #0] ERROR: CUDA error: 0
2020-07-13 12:38:27,043      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7f63cabf3150 at 0x7f6370edaa50>
2020-07-13 12:38:27,047      [GPU #0] ERROR: CUDA error: 1

**Comment by lw** [comment]
An error code of 1 means cudaErrorInvalidValue, so we're passing bad parameters to the cudaHostRegister call. There could be a few options (zero length, null pointer, non-page-aligned pointer, ...). We should print those args.

Could you add this line:
```
logger.error(f"cudaHostRegister args: {s.data_ptr()}, {s.size()}, {s.element_size()}")
```
somewhere in here:
https://github.com/facebookresearch/PyTorch-BigGraph/blob/4ca238f7d27a6e720b30587f326dd5a40315cc88/torchbiggraph/train_gpu.py#L151-L154
and then re-run?

**Comment by vadimosipov** [comment]
@lw , sure.

**Comment by vadimosipov** [comment]
A couple of things that might be interesting:
pytorch==1.5.1
cudatoolkit==10.1.243
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Linux 109cd1e307ad 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


First time when I was trying to build the project with gpu enabled, I faced with an error:
Building wheel for torchbiggraph (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/envs/pytorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-tgt_8no0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-tgt_8no0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dmk3cq5u
       cwd: /tmp/pip-req-build-tgt_8no0/
  Complete output (80 lines):
  which: no hipcc in (/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/appuser/.conda/envs/factory/bin)
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
  running bdist_wheel
  /opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py:305: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
	
  !! WARNING !!
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
  Please use a compiler that is ABI-compatible with GCC 5.0 and above.
  See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
  
  See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
  for instructions on how to install GCC 5 or higher.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


And I noticed 2 things the building requires hipcc and g++ 5.0 and above.
When I installed devtoolset-9, and rebuilt it again, PBG was installed successfully.
But I did not install hipcc (rocm-dkms or similar) and according to a comment in train_gpu.py # FIXME: broken by D20249187
I can see that PyTorch itself uses HIP (https://github.com/pytorch/pytorch/commit/5fc5cf6571f3e33bc5061b3e139a313433ee5ca1)
So, should I install rock-dkms while building the project or having the right version of gcc is enough?
Can it effect on arising the error?

**Comment by vadimosipov** [comment]
@lw , added.
Console output:
2020-07-13 13:11:07,729   [Trainer-0] Loading entity counts...
2020-07-13 13:11:07,730   [Trainer-0] Creating workers...
2020-07-13 13:11:07,830   [Trainer-0] Initializing global model...
2020-07-13 13:11:07,868   [Trainer-0] Creating GPU workers...
2020-07-13 13:11:07,887   [Trainer-0] Starting epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2020-07-13 13:11:07,901   [Trainer-0] Edge path: data/FB15k/freebase_mtr100_mte100-train_partitioned
2020-07-13 13:11:07,902   [Trainer-0] still in queue: 0
2020-07-13 13:11:07,902   [Trainer-0] Swapping partitioned embeddings None ( 0 , 0 )
2020-07-13 13:11:07,903   [Trainer-0] Loading partitioned embeddings from checkpoint
2020-07-13 13:11:09,258      [GPU #0] ERROR: cudaHostRegister args: 140625517588480, 483142, 8
2020-07-13 13:11:09,258      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7fe649c10150 at 0x7fe5efef2d10>
2020-07-13 13:11:11,478      [GPU #0] ERROR: CUDA error: 0
2020-07-13 13:11:11,480      [GPU #0] ERROR: cudaHostRegister args: 140625521455104, 483142, 8
2020-07-13 13:11:11,480      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7fe649c10150 at 0x7fe5efef6cd0>
2020-07-13 13:11:11,481      [GPU #0] ERROR: CUDA error: 0
2020-07-13 13:11:11,481      [GPU #0] ERROR: cudaHostRegister args: 140625489797120, 483142, 8
2020-07-13 13:11:11,481      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7fe649c10150 at 0x7fe5efef6c50>
2020-07-13 13:11:11,482      [GPU #0] ERROR: CUDA error: 0
2020-07-13 13:11:11,482      [GPU #0] ERROR: cudaHostRegister args: 140625525321728, 5980400, 4
2020-07-13 13:11:11,482      [GPU #0] ERROR: CUDA cudart: <CDLL 'None', handle 7fe649c10150 at 0x7fe5efef6c10>
2020-07-13 13:11:11,486      [GPU #0] ERROR: CUDA error: 1
Process GPU #0:

**Comment by lw** [comment]
Nothing looks off there... I don't really know what else to try.

A couple of generic questions: what card do you have? If it's somewhat old it may not support some features we need. Also, could there perhaps be a limit on your machine on how much memory each process is allowed to page-lock? I know such a limit can be set but I don't remember how.

**Comment by vadimosipov** [comment]
$ nvidia-smi -q

==============NVSMI LOG==============

Timestamp                           : Mon Jul 13 14:02:18 2020
Driver Version                      : 418.67
CUDA Version                        : 10.1

Attached GPUs                       : 1
GPU 00000000:03:00.0
    Product Name                    : Tesla P100-PCIE-16GB
    Product Brand                   : Tesla
    Display Mode                    : Enabled
    Display Active                  : Disabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : 0320418056515
    GPU UUID                        : GPU-ec315101-2c81-1317-1df0-43cfb01564c1
    Minor Number                    : 0
    VBIOS Version                   : 86.00.4D.00.01
    MultiGPU Board                  : No
    Board ID                        : 0x300
    GPU Part Number                 : 900-2H400-0000-000
    Inforom Version
        Image Version               : H400.0201.00.08
        OEM Object                  : 1.1
        ECC Object                  : 4.1
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization mode         : None
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x03
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x15F810DE
        Bus Id                      : 00000000:03:00.0
        Sub System Id               : 0x118F10DE
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 3
            Link Width
                Max                 : 16x
                Current             : 16x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 0 KB/s
        Rx Throughput               : 0 KB/s
    Fan Speed                       : N/A
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 16280 MiB
        Used                        : 673 MiB
        Free                        : 15607 MiB
    BAR1 Memory Usage
        Total                       : 16384 MiB
        Used                        : 2 MiB
        Free                        : 16382 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : Enabled
        Pending                     : Enabled
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : N/A
                L2 Cache            : 0
                Texture Memory      : 0
                Texture Shared      : 0
                CBU                 : N/A
                Total               : 0
            Double Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : N/A
                L2 Cache            : 0
                Texture Memory      : 0
                Texture Shared      : 0
                CBU                 : N/A
                Total               : 0
        Aggregate
            Single Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : N/A
                L2 Cache            : 0
                Texture Memory      : 0
                Texture Shared      : 0
                CBU                 : N/A
                Total               : 0
            Double Bit            
                Device Memory       : 0
                Register File       : 0
                L1 Cache            : N/A
                L2 Cache            : 0
                Texture Memory      : 0
                Texture Shared      : 0
                CBU                 : N/A
                Total               : 0
    Retired Pages
        Single Bit ECC              : 0
        Double Bit ECC              : 0
        Pending                     : No
    Temperature
        GPU Current Temp            : 46 C
        GPU Shutdown Temp           : 85 C
        GPU Slowdown Temp           : 82 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : 35.09 W
        Power Limit                 : 250.00 W
        Default Power Limit         : 250.00 W
        Enforced Power Limit        : 250.00 W
        Min Power Limit             : 125.00 W
        Max Power Limit             : 250.00 W
    Clocks
        Graphics                    : 1189 MHz
        SM                          : 1189 MHz
        Memory                      : 715 MHz
        Video                       : 1075 MHz
    Applications Clocks
        Graphics                    : 1189 MHz
        Memory                      : 715 MHz
    Default Applications Clocks
        Graphics                    : 1189 MHz
        Memory                      : 715 MHz
    Max Clocks
        Graphics                    : 1328 MHz
        SM                          : 1328 MHz
        Memory                      : 715 MHz
        Video                       : 1328 MHz
    Max Customer Boost Clocks
        Graphics                    : 1328 MHz
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes

**Comment by vadimosipov** [comment]
I've got a few ideas

1) Let's check environment variables. May be, I should add additional ones.
```
CUDA_PKG_VERSION=10-1-10.1.243-1
CUDA_VERSION=10.1.243
CUDNN_VERSION=7.6.5.32
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/hadoop/lib/native
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_REQUIRE_CUDA=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411
NVIDIA_VISIBLE_DEVICES=all
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

2) Please, tell me, should I install hcc-base, rock-dkms prior to building the project?

3) Please, go over my Dockerfile code:
Dockerfile:
```
ARG IMAGE_NAME
FROM ${IMAGE_NAME}

RUN conda env create --file environment.yaml

ENV CONDA_DEFAULT_ENV="pytorch"

RUN yum install --quiet --assumeyes centos-release-scl \
    && yum --assumeyes update \
    && yum install --quiet --assumeyes devtoolset-9-gcc devtoolset-9-gcc-c++

# COPY rocm.repo /etc/yum.repos.d/
# RUN yum install --quiet --assumeyes rocm-dkms && usermod -a -G video ${APP_USER}

RUN curl -LO https://github.com/facebookresearch/PyTorch-BigGraph/archive/master.zip \
    && unzip master.zip \
    && rm master.zip

SHELL [ "/usr/bin/scl", "enable", "devtoolset-9"]

RUN cd PyTorch-BigGraph-master \
    && export PBG_INSTALL_CPP=1 \
    && conda run python -m pip install .

SHELL ["/bin/bash", "-c"]

RUN curl -LO https://dl.fbaipublicfiles.com/starspace/fb15k.tgz \
    && mkdir data \
    && tar -xf fb15k.tgz -C data
```


environment.yaml:
```
name: pytorch
dependencies:
  - python>=3.7.0
  - pytorch>=1.5.1
  - torchvision
  - cudatoolkit==10.1.243
```

4) I've checked if my build can actually run any code using PyTorch and Cuda. 
I ran the next code (used that article: https://pytorch.org/tutorials/advanced/cpp_extension.html) and it executed successfully.
I really don't understand if PyTorch + Cuda works, what's wrong with my PBG build.
Check it out, please:

```
import torch
import math
from torch.functional import F

class LLTM(torch.nn.Module):
    def __init__(self, input_features, state_size):
        super(LLTM, self).__init__()
        self.input_features = input_features
        self.state_size = state_size
        # 3 * state_size for input gate, output gate and candidate cell gate.
        # input_features + state_size because we will multiply with [input, h].
        self.weights = torch.nn.Parameter(
            torch.empty(3 * state_size, input_features + state_size))
        self.bias = torch.nn.Parameter(torch.empty(3 * state_size))
        self.reset_parameters()

    def reset_parameters(self):
        stdv = 1.0 / math.sqrt(self.state_size)
        for weight in self.parameters():
            weight.data.uniform_(-stdv, +stdv)

    def forward(self, input, state):
        old_h, old_cell = state
        X = torch.cat([old_h, input], dim=1)

        # Compute the input, output and candidate cell gates with one MM.
        gate_weights = F.linear(X, self.weights, self.bias)
        # Split the combined gate weight matrix into its components.
        gates = gate_weights.chunk(3, dim=1)

        input_gate = torch.sigmoid(gates[0])
        output_gate = torch.sigmoid(gates[1])
        # Here we use an ELU instead of the usual tanh.
        candidate_cell = F.elu(gates[2])

        # Compute the new cell state.
        new_cell = old_cell + candidate_cell * input_gate
        # Compute the new hidden state and output.
        new_h = torch.tanh(new_cell) * output_gate

        return new_h, new_cell


import torch

assert torch.cuda.is_available()
cuda_device = torch.device("cuda")  # device object representing GPU

batch_size = 16
input_features = 32
state_size = 128

# Note the device=cuda_device arguments here
X = torch.randn(batch_size, input_features, device=cuda_device)
h = torch.randn(batch_size, state_size, device=cuda_device)
C = torch.randn(batch_size, state_size, device=cuda_device)

rnn = LLTM(input_features, state_size).to(cuda_device)

forward = 0
backward = 0

import time

for _ in range(100000):
    start = time.time()
    new_h, new_C = rnn(X, (h, C))
    torch.cuda.synchronize()
    forward += time.time() - start

    start = time.time()
    (new_h.sum() + new_C.sum()).backward()
    torch.cuda.synchronize()
    backward += time.time() - start

print('Forward: {:.3f} us | Backward {:.3f} us'.format(forward * 1e6/1e5, backward * 1e6/1e5))
```

**Comment by lw** [comment]
You could install hcc-base and rock-dkms. It's unlikely that it will help, but it won't hurt either.

Using Docker may be a risk here. I'm not familiar with it and with whether it introduces problems with CUDA, shared memory and/or page-locked memory. It would definitely be better if you could avoid it and run on bare metal.

Could you also check that the following works in your installation:
```
In [1]: import torch                                                                                                                                                                                                                                                                                              

In [2]: t = torch.empty((1000, 1000, 1000), dtype=torch.uint8).pin_memory()                                                                                                                                                                                                                                       

In [3]: t.is_pinned()                                                                                                                                                                                                                                                                                             
Out[3]: True

In [4]: s = torch.empty((1000, 1000, 1000), dtype=torch.uint8).share_memory_()                                                                                                                                                                                                                                    

In [5]: s.is_shared()                                                                                                                                                                                                                                                                                             
Out[5]: True
```

**Comment by vadimosipov** [comment]
We catched it ! ))

```
ipython
Python 3.7.7 (default, May  7 2020, 21:25:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch                                                                                                                                                               

In [2]: t = torch.empty((1000, 1000, 1000), dtype=torch.uint8).pin_memory()                                                                                                        

In [3]: t.is_pinned()                                                                                                                                                              
Out[3]: True

In [4]: s = torch.empty((1000, 1000, 1000), dtype=torch.uint8).share_memory_()                                                                                                     
Bus error (core dumped)
```

I've re-run again with --ipc=host and it's running ! 

```
2020-07-13 15:31:18,441   [Trainer-0] Loading entity counts...
2020-07-13 15:31:18,442   [Trainer-0] Creating workers...
2020-07-13 15:31:18,535   [Trainer-0] Initializing global model...
2020-07-13 15:31:18,571   [Trainer-0] Creating GPU workers...
2020-07-13 15:31:18,590   [Trainer-0] Starting epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2020-07-13 15:31:18,590   [Trainer-0] Edge path: data/FB15k/freebase_mtr100_mte100-train_partitioned
2020-07-13 15:31:18,591   [Trainer-0] still in queue: 0
2020-07-13 15:31:18,591   [Trainer-0] Swapping partitioned embeddings None ( 0 , 0 )
2020-07-13 15:31:18,592   [Trainer-0] Loading partitioned embeddings from checkpoint
2020-07-13 15:31:22,261      [GPU #0] GPU subprocess 0 up and running
2020-07-13 15:31:28,359   [Trainer-0] ( 0 , 0 ): Speed: 51,064 edges/sec
2020-07-13 15:31:28,366   [Trainer-0] ( 0 , 0 ): Training stats: loss:  7.33105 , reg:  0.215522 , violators_lhs:  88.9899 , violators_rhs:  84.9621 , count:  483142
2020-07-13 15:31:28,366   [Trainer-0] ( 0 , 0 ): bucket 1 / 1 : Trained 483142 edges in 9.62 s ( 0.05 M/sec ); Eval 2*0 edges in 0.00 s ( 0 M/sec ); io: 0.15 s for 35,517,008 bytes ( 235.77 MB/sec )
2020-07-13 15:31:28,367   [Trainer-0] Swapping partitioned embeddings ( 0 , 0 ) None
2020-07-13 15:31:28,367   [Trainer-0] Saving partitioned embeddings to checkpoint
2020-07-13 15:31:28,490   [Trainer-0] Finished epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2020-07-13 15:31:28,490   [Trainer-0] Writing the metadata
2020-07-13 15:31:28,512   [Trainer-0] Writing the training stats
2020-07-13 15:31:28,513   [Trainer-0] Writing the checkpoint
2020-07-13 15:31:28,513   [Trainer-0] Switching to the new checkpoint version
```

Great!
@lw , thank you :)

**Comment by lw** [comment]
Glad this is solved! I'm closing the issue but reopen it if there's something else...

**Comment by malteos** [comment]
In case somebody else encounters the `[Errno 104] Connection reset by peer` error message, this other issue help me: https://github.com/facebookresearch/PyTorch-BigGraph/issues/154
