### ISSUE TITLE
A RuntimeError occurs in distributed mode: "Connection closed by peer [10.24.184.33]:16062"

### ISSUE THREAD

**Issue by miemouwu** [facebookresearch/PyTorch-BigGraph#152]
I used 5 machines and 10 partitions. The process of training  succeeded in the first epoch, but during the second one, an error  occured. The configuration of distribution mode  is as follows:
 ```
        num_machines= 5,
        num_partition_servers = -1,
        distributed_init_method = "env://",
        distributed_tree_init_order = True,

        #Misc
        hogwild_delay = 2,
 ```

## Observed Results

2020-07-28 21:46:10  Swapping partitioned embeddings ( 5 , 2 ) None
2020-07-28 21:46:10  Writing partitioned embeddings
2020-07-28 21:46:31  Swapping partitioned embeddings None None
2020-07-28 21:46:58  Parameter client synced 2833 rounds 0.0022664 GB in 60.0076 s ( 0.0211816 s/round , 3.77686e-05 GB/s)
2020-07-28 21:47:02  Finished epoch 1 path 1 pass 1; checkpointing global state.
2020-07-28 21:47:02  My rank: 4
2020-07-28 21:47:02  Writing the checkpoint...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/parameter_sharing.py", line 371, in _client_thread_loop
    clients[client_idx].update(k, v)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/parameter_sharing.py", line 297, in update
    self._client.swap(key, diff, self._cache[key], accum=True)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/parameter_sharing.py", line 242, in swap
    td.send(cmd_rpc, self.server_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 598, in send
    _default_pg.send([tensor], dst, tag).wait()
RuntimeError: [/opt/conda/conda-bld/pytorch-cpu_1549632688322/work/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.24.184.33]:16062
Process ParameterClient-14:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/parameter_sharing.py", line 371, in _client_thread_loop
    clients[client_idx].update(k, v)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/parameter_sharing.py", line 297, in update
    self._client.swap(key, diff, self._cache[key], accum=True)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/parameter_sharing.py", line 242, in swap
    td.send(cmd_rpc, self.server_rank)
  File "/usr/local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 598, in send
    _default_pg.send([tensor], dst, tag).wait()
RuntimeError: [/opt/conda/conda-bld/pytorch-cpu_1549632688322/work/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [10.24.184.33]:16062

## Expected Results

  * What did you expect to happen?
The whole process of training succeeds.

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by adamlerer** [comment]
It looks like one of the other machines closed the connection ([10.24.184.33]:16062), could you look at that machine's logs and see if there's a more informative error?

**Comment by miemouwu** [comment]
> It looks like one of the other machines closed the connection ([10.24.184.33]:16062), could you look at that machine's logs and see if there's a more informative error?

Sorry to reply so late to you. Here are the last few lines of the log of the machine([10.24.184.33]) and the log of the other 3 machine are almost the same.

2020-07-28 21:45:12  ( 6 , 4 ): loss:  7.07347 , violators_lhs:  0 , violators_rhs:  0 , count:  839177
2020-07-28 21:45:13  stats after ( 6 , 4 ): pos_rank:  377.02 , mrr:  0.196052 , r1:  0.138565 , r10:  0.303337 , r50:  0.429801 , auc:  0.816039 , count:  44167
2020-07-28 21:45:13  Swapping partitioned embeddings ( 6 , 4 ) ( 6 , 1 )
2020-07-28 21:45:13  Writing partitioned embeddings
2020-07-28 21:45:13  Loading entities
2020-07-28 21:45:14  stats before ( 6 , 1 ): pos_rank:  418.708 , mrr:  0.166944 , r1:  0.12017 , r10:  0.250797 , r50:  0.381248 , auc:  0.794746 , count:  42652
2020-07-28 21:45:18  ( 6 , 1 ): bucket 93 / 100 : Processed 853040 edges in 4.06 s ( 0.21 M/sec ); io: 1.05 s ( 515.08 MB/sec )
2020-07-28 21:45:18  ( 6 , 1 ): loss:  6.82351 , violators_lhs:  0 , violators_rhs:  0 , count:  810388
2020-07-28 21:45:18  stats after ( 6 , 1 ): pos_rank:  349.248 , mrr:  0.217232 , r1:  0.16059 , r10:  0.321779 , r50:  0.464562 , auc:  0.826268 , count:  42652
2020-07-28 21:45:18  Swapping partitioned embeddings ( 6 , 1 ) ( 4 , 6 )
2020-07-28 21:45:18  Writing partitioned embeddings
2020-07-28 21:45:27  Loading entities
2020-07-28 21:45:45  stats before ( 4 , 6 ): pos_rank:  386.143 , mrr:  0.168698 , r1:  0.11773 , r10:  0.260645 , r50:  0.396328 , auc:  0.80883 , count:  43001
2020-07-28 21:45:49  ( 4 , 6 ): bucket 96 / 100 : Processed 860020 edges in 4.04 s ( 0.21 M/sec ); io: 26.69 s ( 633.80 MB/sec )
2020-07-28 21:45:49  ( 4 , 6 ): loss:  6.78032 , violators_lhs:  0 , violators_rhs:  0 , count:  817019
2020-07-28 21:45:49  stats after ( 4 , 6 ): pos_rank:  331.837 , mrr:  0.211839 , r1:  0.151555 , r10:  0.322295 , r50:  0.465036 , auc:  0.83569 , count:  43001
2020-07-28 21:45:49  Swapping partitioned embeddings ( 4 , 6 ) None
2020-07-28 21:45:49  Writing partitioned embeddings
2020-07-28 21:45:57  Parameter client synced 2720 rounds 0.002176 GB in 60.0052 s ( 0.0220607 s/round , 3.62635e-05 GB/s)
2020-07-28 21:46:31  Swapping partitioned embeddings None None
2020-07-28 21:46:58  Parameter client synced 2653 rounds 0.0021224 GB in 60.0174 s ( 0.0226225 s/round , 3.53631e-05 GB/s)
2020-07-28 21:47:02  Finished epoch 1 path 1 pass 1; checkpointing global state.
2020-07-28 21:47:02  My rank: 2
2020-07-28 21:47:02  Writing the checkpoint...

**Comment by adamlerer** [comment]
Interesting. I still don't see anything that identifies the original error.
There might be something higher up in the logs where some subprocess died a
little earlier on. Can you upload all the full logs somewhere and I'll take
a look?

**Comment by miemouwu** [comment]
> Interesting. I still don't see anything that identifies the original error. There might be something higher up in the logs where some subprocess died a little earlier on. Can you upload all the full logs somewhere and I'll take a look?
> […](#)

This seems to be because of the checkpoint file being too large. When I changed the embedding dimension from 200 to 100, the program runs correctly. Thanks～
