### ISSUE TITLE
Bad address error in CPU training with GPU mode installed.

### ISSUE THREAD

**Issue by HenryYihengXu** [facebookresearch/PyTorch-BigGraph#155]
## Steps to reproduce

  1. Use cuda 10.1, PyTorch 1.3.1
  2. Clone the repo. Inside it do `PBG_INSTALL_CPP=1 pip3 install .` 
  3. Modify `torchbiggraph/examples/fb15k.py` to only use CPU training.
  4. Run `torchbiggraph/examples/fb15k.py` with the provided CPU config

## Observed Results
```
  Traceback (most recent call last):
  File "/usr/local/bin/torchbiggraph_example_fb15k", line 11, in <module>
    load_entry_point('torchbiggraph===file-.torchbiggraph-VERSION.txt', 'console_scripts', 'torchbiggraph_example_fb15k')()
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/examples/fb15k.py", line 90, in main
    train(train_config, subprocess_init=subprocess_init)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train.py", line 42, in train
    coordinator.train()
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train_cpu.py", line 597, in train
    io_bytes = self._swap_partitioned_embeddings(old_b, cur_b, old_stats)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train_cpu.py", line 815, in _swap_partitioned_embeddings
    entity, part, out=embs, strict=self.strict, force_dirty=force_dirty
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train_cpu.py", line 741, in _load_embeddings
    entity, part, out=out, force_dirty=force_dirty
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/checkpoint_manager.py", line 300, in read
    version, entity, part, out
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/checkpoint_storage.py", line 351, in load_entity_partition
    raise err
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/checkpoint_storage.py", line 344, in load_entity_partition
    embs = load_embeddings(hf, out=out)
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/checkpoint_storage.py", line 168, in load_embeddings
    dataset.read_direct(out.numpy())
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 733, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (file read failed: time = Mon Aug 31 16:53:05 2020
, filename = '/root/PyTorch-BigGraph/model/fb15k/embeddings_all_0.v2.h5', file descriptor = 181, errno = 14, error message = 'Bad address', buf = 0x7fb506106000, total read size = 992192, bytes this sub-read = 992192, bytes actually read = 18446744073709551615, offset = 22935552)
```

## Expected Results

  Expect to get the same training result as without GPU mode installed. In other words, PBG installed by `pip install torchbiggraph` works perfectly fine for CPU training. But PBG installed in this way yields this error for CPU training.

**Comment by lw** [comment]
Does that error happen reliably (even after you retry training) or was it a one-off accident?

Where are you storing your checkpoints? Is it local disk or network disk? In the latter case HDF5 may be getting hitting some errors that it's not expecting and misbehave.

Also, you said you've tried both GPU and CPU training. Have you possibly been mixing them on the same checkpoint? In principle that should work, but it's not something we really test and since they do the partitioning slightly differently it may fail if one mode loads the checkpoints created by the other.

In general, then, we recommend to not run PBG in a docker container as that adds some restrictions that PBG doesn't account for and that could lead to odd errors.

**Comment by AugustKarlstedt** [comment]
I was seeing the same issue when loading `edges_[lhs]_[rhs].h5` files. Turns out the default tmpfs setting limits `/dev/shm` to only 50% of total RAM and this was the source of my issue.
