### ISSUE TITLE
key error in async_adagrad 

### ISSUE THREAD

**Issue by nrc53** [facebookresearch/PyTorch-BigGraph#173]
## Steps to reproduce

  1. Ran the fb15K example on CPU
  2. _____
  3. _____

## Observed Results

Traceback (most recent call last):
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/batching.py", line 83, in call
    return f()
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/batching.py", line 117, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/batching.py", line 160, in process_one_batch
    return self._process_one_batch(model, batch_edges)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/train_cpu.py", line 105, in _process_one_batch
    self.model_optimizer.step(closure=None)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/async_adagrad.py", line 76, in step
    std = local_G.sqrt().add_(group["eps"])
KeyError: 'eps'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/bin/torchbiggraph_example_fb15k", line 10, in <module>
    sys.exit(main())
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/examples/fb15k.py", line 90, in main
    train(train_config, subprocess_init=subprocess_init)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/train.py", line 42, in train
    coordinator.train()
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/train_cpu.py", line 661, in train
    stats = self._coordinate_train(edges, eval_edge_idxs, epoch_idx)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/train_cpu.py", line 859, in _coordinate_train
    all_stats = get_async_result(future_all_stats, self.pool)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchbiggraph/util.py", line 332, in get_async_result
    res = future_res.get(health_check_interval)
  File "/home/mdl/nrc53/softwares/power-mc/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: 'eps'

## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by lw** [comment]
@adamlerer could you take a look at this, since you contributed the async adagrad optimizer that is failing?

@nrc53 could you provide a few more details on your setup? for example which Python and PyTorch versions you're using. and anything else you think could be relevant. thanks!

**Comment by adamlerer** [comment]
@nrc53 thanks for reporting. Can you check your pytorch version as follows and report back?

```
python -c "import torch; print(torch.version.__version__)"
```

Thanks.

I guess inheriting from `Adagrad` here was a bad idea because we now have a dependency on the `Adagrad` implementation in Pytorch which may change. 

https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/async_adagrad.py#L5

Fix will probably be to copy-paste the whole Adagrad implementation from torch-1.4 into `torchbiggraph/'

**Comment by nrc53** [comment]
Hi, 

Thanks for your reply. 

I got the error with below versions. 
PyTorch: 1.1.0
Python: 3.6.8

Error got resolved in the below versions.
PyTorch: 1.7.0
Python: 3.7.9

**Comment by lw** [comment]
Glad to hear you've found a way to solve the issue! Indeed, we mostly run and test PBG using very recent versions of PyTorch, and thus we sometimes break compatibility with older ones. We could try to be more careful but, to be honest, newer versions of PyTorch typically carry features we'd like to be able to use, and we feel that it's not too hard for users to update PyTorch if needed. Unfortunately it's hard to keep track of what's the oldest version that's supported. We think PBG should work with version 1.4 at the moment, but version 1.1 is apparently incompatible.

**Comment by nrc53** [comment]
Thank you!
