### ISSUE TITLE
Error while training in GPU (Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!)

### ISSUE THREAD

**Issue by dbanka** [facebookresearch/PyTorch-BigGraph#178]
I tried train pytorch big graph on gpu machine with 8 gpus. 

These are the parameters in my config:
      dynamic_relations=False,
        dimension=100,
        global_emb=False,
        comparator="dot",
        num_epochs=50,
        batch_size=10000,
        num_uniform_negs=1000,
        loss_fn="softmax",
        lr=0.1,
        regularization_coef=1e-3,
        eval_fraction=0.01,
        num_gpus=8,

This is the error I am getting: 
```
home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
Process GPU #0:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_gpu.py", line 184, in run
    lr=job.lr,
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_gpu.py", line 291, in do_one_job
    batch_size=batch_size, model=model, batch_processor=trainer, edges=gpu_edges
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py", line 117, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py", line 160, in process_one_batch
    return self._process_one_batch(model, batch_edges)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_cpu.py", line 90, in _process_one_batch
    scores, reg = model(batch_edges)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/model.py", line 702, in forward
    rhs_negative_sampling_method,
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/model.py", line 855, in forward_direction_agnostic
    reg = self.regularizer.forward(src_pos, dst_pos, operator)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/regularizers.py", line 93, in forward
    total += torch.sum(operator.prepare_embs_for_reg(x) ** 3)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py:31: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  cutpoints = (delta.nonzero().flatten() + 1).tolist()
Process GPU #1:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_gpu.py", line 184, in run
    lr=job.lr,
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_gpu.py", line 291, in do_one_job
    batch_size=batch_size, model=model, batch_processor=trainer, edges=gpu_edges
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py", line 117, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/batching.py", line 160, in process_one_batch
    return self._process_one_batch(model, batch_edges)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_cpu.py", line 90, in _process_one_batch
    scores, reg = model(batch_edges)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/model.py", line 702, in forward
    rhs_negative_sampling_method,
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/model.py", line 855, in forward_direction_agnostic
    reg = self.regularizer.forward(src_pos, dst_pos, operator)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/regularizers.py", line 93, in forward
    total += torch.sum(operator.prepare_embs_for_reg(x) ** 3)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/torchbiggraph_train", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train.py", line 71, in main
    train(config, rank=opt.rank, subprocess_init=subprocess_init)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train.py", line 42, in train
    coordinator.train()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_cpu.py", line 667, in train
    stats = self._coordinate_train(edges, eval_edge_idxs, epoch_idx)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_gpu.py", line 619, in _coordinate_train
    gpu_idx, result = self.gpu_pool.wait_for_next()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/train_gpu.py", line 368, in wait_for_next
    res = p.master_endpoint.recv()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by lw** [comment]
Seems like the real error is this one:
```
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torchbiggraph/regularizers.py", line 93, in forward
    total += torch.sum(operator.prepare_embs_for_reg(x) ** 3)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
And it looks like it happens in the regularization code.

@adamlerer Could you check whether the regularization code supports GPU mode? Also, do we have tests for GPU mode and/or regularization (and their combinations)? Thanks!

As a workaround, could you try disabling regularization? I guess that could be done by setting `regularization_coef` to zero.

**Comment by shitian007** [comment]
Hi I met with the same error a few weeks ago and simply updated the device in `regularizers.py` to get it working for GPU. Had submitted a one-line fix maybe you can take a look https://github.com/facebookresearch/PyTorch-BigGraph/pull/177

**Comment by dbanka** [comment]
thanks @lw  and @shitian007 , I will give it a try
