### ISSUE TITLE
GPU Training works with 4 GPUs but not 8 GPUs

### ISSUE THREAD

**Issue by alimousavi1988** [facebookresearch/PyTorch-BigGraph#190]
This bug is about running the FB15k example using `fb15k_config_gpu.py`.

When I use `num_gpus=1` or `num_gpus=4`, The code runs smoothly. However, when I set `num_gpus=8`, I get the following error:

```
Traceback (most recent call last):
  File "/home/ssm-user/anaconda3/envs/biggraph/bin/torchbiggraph_train", line 8, in <module>
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torchbiggraph/train.py", line 71, in main
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torchbiggraph/train.py", line 42, in train
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torchbiggraph/train_cpu.py", line 667, in train
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torchbiggraph/train_gpu.py", line 617, in _coordinate_train
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torchbiggraph/train_gpu.py", line 612, in schedule
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torchbiggraph/train_gpu.py", line 353, in schedule
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/connection.py", line 206, in send
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 322, in reduce_storage
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/weakref.py", line 648, in _exitfunc
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/weakref.py", line 572, in __call__
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/tempfile.py", line 797, in _cleanup
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/shutil.py", line 490, in rmtree
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/shutil.py", line 488, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/torchbiggraph_config_ke5laxht'
Traceback (most recent call last):
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/util.py", line 300, in _run_finalizers
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/util.py", line 224, in __call__
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/multiprocessing/util.py", line 133, in _remove_temp_dir
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/shutil.py", line 490, in rmtree
  File "/home/ssm-user/anaconda3/envs/biggraph/lib/python3.7/shutil.py", line 488, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/pymp-_9k8hfdh'
```

I would appreciate it if you take a look at this.

**Comment by lw** [comment]
What is your current limit on open file descriptors per process? You can find it with `ulimit -n`. If it seems too low you should increase it, and the way to do so depends on your operating system. Also, if you're running PBG inside Docker or some other container, try running it on "bare metal", as containers introduce a lot of limitations.
