### ISSUE TITLE
ERROR FileNotFoundException "dynamic_rel_names.json" while using "export_to_tsv" command

### ISSUE THREAD

**Issue by kimtox** [facebookresearch/PyTorch-BigGraph#211]
## Steps to reproduce

  1. I've tried to export embeddings from PBG to tsv format.
  2. Set the flag "dynamic_relations" to False.
  3. Run command "torchbiggraph_export_to_tsv --entities-output {embed_path} --relation-types-output {relation_path} {config_path}"
  4. Had the mistake described below
  5. At the same time tsv file was created and saved.

## Observed Results
My log output:

```Done exporting entity data to /repo/skill_search/topics_data/pbg_embeddings
Writing relation type parameters...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torchbiggraph/graph_storages.py", line 178, in load_names
    with path.open("rt") as tf:
  File "/opt/conda/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/conda/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/repo/skill_search/topics_data/entities/dynamic_rel_names.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/torchbiggraph_export_to_tsv", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 151, in main
    make_tsv(
  File "/opt/conda/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 52, in make_tsv
    make_tsv_for_relation_types(
  File "/opt/conda/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 94, in make_tsv_for_relation_types
    relation_types = relation_type_storage.load_names()
  File "/opt/conda/lib/python3.8/site-packages/torchbiggraph/graph_storages.py", line 255, in load_names
    return load_names(self.get_names_file())
  File "/opt/conda/lib/python3.8/site-packages/torchbiggraph/graph_storages.py", line 181, in load_names
    raise CouldNotLoadData() from err
torchbiggraph.util.CouldNotLoadData
Paths pbg_repos_embeddings is /repo/skill_search/topics_data/pbg_repos_embeddings.tsv
```

## Expected Results

I've checked the class _export_to_tsv_ and got to the conclusion that the method _load_names()_ will launch without parameters in any case (no matter is _dynamic_realtion_ option true or false):
``` def load_names(self) -> List[str]:
        return load_names(self.get_names_file())

def get_names_file(self) -> Path:
        return self.path / f"dynamic_rel_names.json"
```

Is it expected behavior of using this method?
Could you please suggest to me the way to avoid this? I'm a newbie in DS so there could be some misunderstanding of the process from my side.
If the only way is to create the _dynamic_rel_names.json_ file could you give me an example of this file?

## Relevant Code

The method which was used in my code
  ```
def get_export_command():
    embed_path = get_setting('pbg_embeddings')
    relation_path=get_setting('entities') + '/relation.tsv'
    config_path = get_setting('pbg_config')

    return 'torchbiggraph_export_to_tsv --entities-output {} --relation-types-output {} {}'.format(
         embed_path, relation_path, config_path
    )
  ```

My config file
```
def get_torchbiggraph_config():
    config = dict(
        # I/O data
        entity_path=get_setting('entities'),
        edge_paths=[get_setting('processed_edges') + '/edgelist_partitioned'],
        checkpoint_path=get_setting('pbg_checkpoints'),

        # Graph structure
        entities={
            'repo': {'num_partitions': int(get_setting('pbg_partitions', 'Params'))},
            'user': {'num_partitions': int(get_setting('pbg_partitions', 'Params'))}
        },
        relations=[{
            'name': 'follow',
            'lhs': 'user',
            'rhs': 'user',
        },
        {
            'name': 'watcher',
            'lhs': 'user',
            'rhs': 'repo',
        }
        ],

        global_emb=False,
        # Scoring model
        dimension=int(get_setting('pbg_embeddings_dim', 'Params')),
        comparator='cos',

        # Training
        num_epochs=10,
        lr=0.001,
        num_edge_chunks=5,
        batch_size=5 * 10 ** 3,
        # Misc
        hogwild_delay=2,
        dynamic_relations=False
    )

    return config
```

**Comment by lw** [comment]
This does kind of look like a bug, sorry about that. Could try applying this patch locally and see if it fixes the problem for you? https://github.com/facebookresearch/PyTorch-BigGraph/pull/212 You'll have to re-import the data and re-train your model unfortunately, sorry.

**Comment by kimtox** [comment]
> This does kind of look like a bug, sorry about that. Could try applying this patch locally and see if it fixes the problem for you? #212 You'll have to re-import the data and re-train your model unfortunately, sorry.

Thank you so much! 
Now it works with a smaller amount of data but I think that everything will be OK with the bigger one. By the way, I had to clone the master repo and use 
```
pip install .
```
command instead 
```
pip install torchbiggraph
```
because in the last case I just didn't have some files from your library including _importers.py_

**Comment by lw** [comment]
Glad to hear the fix worked!

As for the difference between installing from the repo vs installing from PyPI, that's "expected" because on PyPI there's only v1.0 (release 2 years ago), whereas the GitHub version contains a few more recent additions.

**Comment by tmarkovich** [comment]
@adamlerer @lw should we close this issue now that #212 fixes it?
