### ISSUE TITLE
Affine Operator Throws EORError on GPU Training

### ISSUE THREAD

**Issue by tmarkovich** [facebookresearch/PyTorch-BigGraph#235]
## Steps to reproduce

I changed the operator on the FB15k example config from `complex_diagonal` to `affine`, and then reran the basic training steps. 

## Observed Results

BigGraph threw the following error:

```
2021-08-31 00:21:23,975   [Trainer-0] Loading entity counts...
2021-08-31 00:21:23,976   [Trainer-0] Creating workers...
2021-08-31 00:21:32,914   [Trainer-0] Initializing global model...
2021-08-31 00:21:54,975   [Trainer-0] Creating GPU workers...
2021-08-31 00:21:54,984   [Trainer-0] Starting epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2021-08-31 00:21:54,985   [Trainer-0] Edge path: data/FB15k/freebase_mtr100_mte100-train_partitioned/
2021-08-31 00:21:54,985   [Trainer-0] still in queue: 0
2021-08-31 00:21:54,985   [Trainer-0] Swapping partitioned embeddings None ( 0 , 0 )
2021-08-31 00:21:54,985   [Trainer-0] Loading partitioned embeddings from checkpoint
2021-08-31 00:21:56,304      [GPU #0] GPU subprocess 0 up and running
Process GPU #0:
Traceback (most recent call last):
  File "/opt/ee/python/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train_gpu.py", line 181, in run
    lr=job.lr,
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train_gpu.py", line 288, in do_one_job
    batch_size=batch_size, model=model, batch_processor=trainer, edges=gpu_edges
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/batching.py", line 122, in process_in_batches
    all_stats.append(batch_processor.process_one_batch(model, batch_edges))
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/batching.py", line 165, in process_one_batch
    return self._process_one_batch(model, batch_edges)
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train_cpu.py", line 90, in _process_one_batch
    scores, reg = model(batch_edges)
  File "/home/sandbox/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/model.py", line 737, in forward
    Negatives.NONE,
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/model.py", line 853, in forward_direction_agnostic
    reg = self.regularizer.forward_dynamic(src_pos, dst_pos, operator, rel)
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/regularizers.py", line 73, in forward_dynamic
    operator_params = operator.get_operator_params_for_reg(rel_idxs)
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/operators.py", line 193, in get_operator_params_for_reg
    raise NotImplementedError("Regularizer not implemented for this operator")
NotImplementedError: Regularizer not implemented for this operator
Traceback (most recent call last):
  File "../.local/bin/torchbiggraph_train", line 11, in <module>
    load_entry_point('torchbiggraph', 'console_scripts', 'torchbiggraph_train')()
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train.py", line 71, in main
    train(config, rank=opt.rank, subprocess_init=subprocess_init)
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train.py", line 42, in train
    coordinator.train()
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train_cpu.py", line 667, in train
    stats = self._coordinate_train(edges, eval_edge_idxs, epoch_idx)
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train_gpu.py", line 618, in _coordinate_train
    gpu_idx, result = self.gpu_pool.wait_for_next()
  File "/home/sandbox/workspace/PyTorch-BigGraph-5904bb6b57a18bf57c409f5e99f7668a76d504b2/torchbiggraph/train_gpu.py", line 365, in wait_for_next
    res = p.master_endpoint.recv()
  File "/opt/ee/python/3.7/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/ee/python/3.7/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/ee/python/3.7/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

## Expected Results

I expected it to training.

## Relevant Code

I'm running pytorch=1.7.0+cu110.

## Notes

Thanks for the great library! I'm happy to help get this up and running if you need a hand.

**Comment by lw** [comment]
I think you missed this line in the logs which explains the problem:
```
NotImplementedError: Regularizer not implemented for this operator
```

You could either disable regularizers, use a different operator, or contribute a regularizer.

**Comment by tmarkovich** [comment]
Of course, I should have read more clearly. That's what I get for playing around bleary eyed.

Just to check, the reason that N3 isn't used for linear operators is because the regularizer defined in https://arxiv.org/pdf/1806.07297.pdf right below section 4.1 doesn't quite make sense for a 2-rank u_r^(2) but it does make sense for a 1-rank u_r^(2)? Or rather, the rest of the derivation of the regularizer only holds if it's a vector?

**Comment by lw** [comment]
I think regularizers were contributed recently by @adamlerer and @timlacroix, maybe they can weigh in?

**Comment by timlacroix** [comment]
@tmarkovich I'm not sure I understood the regularizer you propose, what are u_r^{(1)}, u_r^{(2)} and u_r^{(3)} ?

To me the task `|| M_r h - M_r t ||^2` is closer to the transE task `|| h + r - t ||^2` (see for example this transE variation : https://www.aaai.org/ocs/index.php/AAAI/AAAI15/paper/viewFile/9571/9523/ ), which is usually regularized with weight decay.

Computing the entire products ||M_r H || and ||M_r T|| for all r to penalize their frobenius norm squared seems slow if you have many relations ?  I would suggest minimizing ||H||_F^2, ||T||_F^2 and \sum_r ||M_r||_F^2  ?

For a score of `<M_r h, M_rt>`, you would be learning a tucker factorization of your representation, and I've always found these to be difficult to learn and regularize properly (see for example https://openreview.net/pdf?id=ByeAK1BKPB that tells about my attempts with this representation).

Hopefully, using ||M_r h - M_r t||^2 works in your case, in which case the simple regularizer described above should be good enough :)

Regarding the actual implementation, it has been a while since I've seen this codebase. Maybe you can try something and me,  @adamlerer  or @lw  can look at the diff ?

**Comment by tmarkovich** [comment]
@timlacroix oh, I was borrowing the notation from https://arxiv.org/pdf/1806.07297.pdf where the 3 u's were just low-rank tensors from the CP decomposition.

Anyway, I guess let me begin by checking my understanding a bit. For the `translation` operator, the task is ultimately to find a low-rank approximation of X as

X = e \otimes r \otimes e

where h, t \in e, and subject to something that looks < g_t (h, r; \theta), g_noop(t) > where g_t = h + \theta_r (and  where here transE uses a cosine inner product). With that in mind, following the KBC paper, we find that eqn gives us that the regularization is `|| h ||^3 + ||r||^3 + ||t||^3`; which I think we can see in the code, where we get ||r|| at [1] and ||h|| at [2]. Is that correct?

If that's correct, then it seems like it's indeed the case that a method like transR wouldn't actually be all that similar in spirit to transE due to the presence of the linear map. Would it be the case that transR is some variant of a tucker decomposition (as you pointed out) where, I think, U_1 = U_3, and we recover M_r from U_2 [4]. In any event, your paper provides a reasonably compelling explanation as to why this is challenging. I do wonder if we can get "close enough" by saying that `||M_r h + r - M_r t||` -> `||h + M_r^{-1} r - t ||`, which would then allow us to potentially regularize by `|| h ||^3 + ||M^{-1}_r r||^3 + ||t||^3`, assuming that `M_r` is invertible, but I'm guessing that `M_r` should be invertible in spirit even if not so numerically. Although, maybe your suggestion of ` \sum_r ||M_r||_F^2` is close enough to work given that `M^-1` and `M` will have the same rank (and this is ultimately meant as convex relaxation for the rank norm) assuming that an inverse exists (and the pseudo-inverses have the same rank).

[1] https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/operators.py#L84
[2] https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/operators.py#L43
[3] https://www.aaai.org/ocs/index.php/AAAI/AAAI15/paper/viewFile/9571/9523/
[4] I'm likely wrong on this one -- I've not had much time to think about this deeply yet.

**Comment by timlacroix** [comment]
@tmarkovich for the translation operator, depending on the comparator, you're either writing X as <h + r, t> or ||h+r-t||. Both of these should be regularized with the usual frobenius norm squared. Going to higher order regularizer can be useful when an element of X is of order three, like in <h, r, t>. <h+r, t> and ||h+r-t|| are both of order two.

Not sure what you mean by `|M_r h + r - M_r t|| -> ||h + M_r^{-1} r - t ||` ? if the arrow is an equality, this isn't true in general, M_r would need to preserve the norms.

I think your original proposal to penalize ||M_r h|| and ||M_r t|| is good. I'd just use ||.||_2^2 for this penalty.

**Comment by tmarkovich** [comment]
@timlacroix thanks for explaining that. I guess what this is ultimately bringing to light is that I don't really understand how translation based methods can be mapped to factorization based methods but I've not seen much in the literature on this topic. Do you happen to a reference or two on the matter?

Also, I meant the arrow, roughly, if we assume the norm is preserved, the minima would be the same in both instances. As I think a little more about it, that's probably never going to be the case. And the regularizer did work fine but was pretty slow. I suppose that it's probably worth implementing a weight decay regularizer.
