### ISSUE TITLE
embedding multi relation graph which relations are sentences and entities are wikipedia titles.

### ISSUE THREAD

**Issue by zahramahani** [facebookresearch/PyTorch-BigGraph#243]
## Steps to reproduce

  1. data set sample:
  ```
  [
        ['Barack_Obama', 'Barack Hussein Obama II (/bəˈrɑːk huːˈseɪn oʊˈbɑːmə/ (About this soundlisten) bə-RAHK hoo-SAYN oh-BAH-mə;[1] born August 4, 1961) is an American politician, lawyer, and author who served as the 44th president of the United States from 2009 to 2017', 'president_of_the_United_States'],
        ['Barack_Obama', 'He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004.', 'United_States_Senate'],
        ['Barack_Obama', 'He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004.', 'Illinois'],
        ['Barack_Obama', 'He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004.', 'Illinois_Senate'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.', 'Upper_house'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.',  'United_States_Congress'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.',  'United_States_House_of_Representatives'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.',  'Lower_house'],
        ['Illinois', 'Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state', 'Chicago'],
        ['Illinois', 'Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state',  'List_of_United_States_cities_by_population'],
        ['Illinois', 'Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state', 'Springfield,_Illinois']
    ]
```
  2. config file:
  ```
raw_config = dict(
        # I/O data
        entity_path=DATA_DIR,
        edge_paths=[
            DATA_DIR + '/edges_partitioned',
        ],
        checkpoint_path=MODEL_DIR,
        # Graph structure
        entities={
            "pages": {"num_partitions": 1}
        },
        relations=[
            {
                "name": "connecting_sentence",
                "lhs": "pages",
                "rhs": "pages",
                "operator": "complex_diagonal",
            }
        ],
        dynamic_relations=True,

      # Scoring model
        dimension=512,
        global_emb=False,
        comparator='cos',

        # Training
        num_epochs=4,
        num_edge_chunks=10,
        batch_size=10000,
        num_batch_negs=500,
        num_uniform_negs=500,
        loss_fn='softmax',
        lr=0.1,
        relation_lr=0.01,

        # Evaluation during training
        eval_fraction=0.001,
        eval_num_batch_negs=10000,
        eval_num_uniform_negs=0,

        # Misc
        verbose=1,
    )
```

## Observed Results

  relations and entities cant be extracted correctly.
  relations which extracted in dynamic_rel_names.json  :
  ```
  [
    "Obama",
    "States",
    "Chicago"
     ]
```
entities which extracted in entity_names_pages_0.json :
```
[
    "Senate",
    "Illinois",
    "Barack",
    "is",
    "He",
    "United"
]
```
## Expected Results
relations which extracted in dynamic_rel_names.json  :
```
  [
     "Barack Hussein Obama II (/bəˈrɑːk huːˈseɪn oʊˈbɑːmə/ (About this soundlisten) bə-RAHK hoo-SAYN oh-BAH-mə;[1] born August 4, 1961) is an American politician, lawyer, and author who served as the 44th president of the United States from 2009 to 2017",
      "He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004."
      "The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber."
      "Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state"
    ]
```
entities which extracted in entity_names_pages_0.json :
  ```
  [
        '"Barack_Obama",
        "president_of_the_United_States",
         "United_States_Senate",
         "Illinois",
         "Illinois_Senate",
         "Upper_house",
        "United_States_Congress",
        "United_States_House_of_Representatives",
        "Lower_house",
        "Chicago",
       "List_of_United_States_cities_by_population",
        "Springfield,_Illinois"
    ]
```

## Observed Results 2

I got error :
```
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "test_big_graph.py", line 141, in <module>
    train(config, subprocess_init=subprocess_init)
  File "/programs/miniconda3/lib/python3.8/site-packages/torchbiggraph/train.py", line 42, in train
    coordinator.train()
  File "/programs/miniconda3/lib/python3.8/site-packages/torchbiggraph/train_cpu.py", line 667, in train
    stats = self._coordinate_train(edges, eval_edge_idxs, epoch_idx)
  File "/programs/miniconda3/lib/python3.8/site-packages/torchbiggraph/train_cpu.py", line 865, in _coordinate_train
    all_stats = get_async_result(future_all_stats, self.pool)
  File "/programs/miniconda3/lib/python3.8/site-packages/torchbiggraph/util.py", line 345, in get_async_result
    raise RuntimeError(
RuntimeError: A subprocess exited unexpectedly with status 0

```
## Expected Results

  * how to resolve this error?

## Relevant Code
compelete code is:
  ```
  import os
import shutil
import json
import h5py
from pathlib import Path
from torchbiggraph.config import parse_config
from torchbiggraph.converters.importers import TSVEdgelistReader, convert_input_data
from torchbiggraph.train import train
from torchbiggraph.util import SubprocessInitializer, setup_logging

DATA_DIR = '/content/data/example_2'
GRAPH_PATH = DATA_DIR + '/edges.tsv'
MODEL_DIR = '/content/model_2'


if __name__ == '__main__':
    try:
        shutil.rmtree('data')
    except:
        pass
    try:
        shutil.rmtree('model_2')
    except:
        pass

    print('inside  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM')
    # ==================================================================
    # 0. PREPARE THE GRAPH
    # the result of this step is a single file 'data/example_2/graph.tsv'
    # ==================================================================

    # This the graph we will be embedding.
    edges = [
        ['Barack_Obama', 'Barack Hussein Obama II (/bəˈrɑːk huːˈseɪn oʊˈbɑːmə/ (About this soundlisten) bə-RAHK hoo-SAYN oh-BAH-mə;[1] born August 4, 1961) is an American politician, lawyer, and author who served as the 44th president of the United States from 2009 to 2017', 'president_of_the_United_States'],
        ['Barack_Obama', 'He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004.', 'United_States_Senate'],
        ['Barack_Obama', 'He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004.', 'Illinois'],
        ['Barack_Obama', 'He previously served as a U.S. senator from Illinois from 2005 to 2008 and as an Illinois state senator from 1997 to 2004.', 'Illinois_Senate'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.', 'Upper_house'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.',  'United_States_Congress'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.',  'United_States_House_of_Representatives'],
        ['United_States_Senate', 'The United States Senate is the upper chamber of the United States Congress, with the House of Representatives being the lower chamber.',  'Lower_house'],
        ['Illinois', 'Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state', 'Chicago'],
        ['Illinois', 'Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state',  'List_of_United_States_cities_by_population'],
        ['Illinois', 'Chicago is the states largest city and the fifth largest city in North America with the capital in Springfield, located in the center of the state', 'Springfield,_Illinois']
    ]

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(GRAPH_PATH, 'w') as f:
        for edge in edges:
            f.write('\t'.join(edge) + '\n')

    # ==================================================
    # 1. DEFINE CONFIG
    # this dictionary will be used in steps 2. and 3.
    # ==================================================

    raw_config = dict(
        # I/O data
        entity_path=DATA_DIR,
        edge_paths=[
            DATA_DIR + '/edges_partitioned',
        ],
        checkpoint_path=MODEL_DIR,
        # Graph structure
        entities={
            "pages": {"num_partitions": 1}
        },
        relations=[
            {
                "name": "connecting_sentence",
                "lhs": "pages",
                "rhs": "pages",
                "operator": "complex_diagonal",
            }
        ],
        dynamic_relations=True,

      # Scoring model
        dimension=512,
        global_emb=False,
        comparator='cos',

        # Training
        num_epochs=4,
        num_edge_chunks=10,
        batch_size=10000,
        num_batch_negs=500,
        num_uniform_negs=500,
        loss_fn='softmax',
        lr=0.1,
        relation_lr=0.01,

        # Evaluation during training
        eval_fraction=0.001,
        eval_num_batch_negs=10000,
        eval_num_uniform_negs=0,

        # Misc
        verbose=1,
    )

    # =================================================
    # 2. TRANSFORM GRAPH TO A BIGGRAPH-FRIENDLY FORMAT
    # This step generates the following metadata files:
    #
    # data/example_2/entity_count_pages_0.txt
    # data/example_2/entity_names_pages_0.json
    #
    # and this file with data:
    # data/example_2/edges_partitioned/edges_0_0.h5
    # =================================================
    setup_logging()
    config = parse_config(raw_config)
    subprocess_init = SubprocessInitializer()
    input_edge_paths = [Path(GRAPH_PATH)]

    convert_input_data(
        config.entities,
        config.relations,
        config.entity_path,
        config.edge_paths,
        input_edge_paths,
        TSVEdgelistReader(lhs_col=0, rel_col=1, rhs_col=2),
        dynamic_relations=config.dynamic_relations,
    )

    # ===============================================
    # 3. TRAIN THE EMBEDDINGS
    # files generated in this step:
    #
    # checkpoint_version.txt
    # config.json
    # embeddings_pages_0.v7.h5
    # model.v7.h5
    # training_stats.json
    # ===============================================

    train(config, subprocess_init=subprocess_init)

    # =======================================================================
    # 4. LOAD THE EMBEDDINGS
    # The final output of the process consists of 1 dictionary -
    # - one for pages- mapping entity to its embedding
    # =======================================================================
    pages_path = DATA_DIR + '/entity_names_pages_0.json'


    pages_emb_path = MODEL_DIR + "/embeddings_pages_0.v{NUMBER_OF_EPOCHS}.h5" \
        .format(NUMBER_OF_EPOCHS=raw_config['num_epochs'])
   
    with open(pages_path, 'r') as f:
        users = json.load(f)

    with h5py.File(pages_emb_path, 'r') as g:
        user_embeddings = g['embeddings'][:]

    pages2embedding = dict(zip(users, user_embeddings))
    print('pages embeddings')
    print(pages2embedding)
    print()
  ```

**Comment by lw** [comment]
```
OSError: [Errno 24] Too many open files
```
This probably means your system has a too low limit on how many file descriptors a process can have. You can check that with `ulimit -n`. The steps to change this value depend on your system so I suggest you Google how to do that.

**Comment by zahramahani** [comment]
can i ask you to help me for setting config file properly that my relations and entities can be identified currectly?


with regards.

**Comment by lw** [comment]
Try replacing
```
TSVEdgelistReader(lhs_col=0, rel_col=1, rhs_col=2),
```
with
```
TSVEdgelistReader(lhs_col=0, rel_col=1, rhs_col=2, delimiter="\t"),
```
