### ISSUE TITLE
No module named 'filtered_eval'

### ISSUE THREAD

**Issue by animesh** [facebookresearch/PyTorch-BigGraph#28]
## Steps to reproduce
Executing the script:
  ```
https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/examples/fb15k.py
  ```
shows following error
```

 $ python fb15k.py
Traceback (most recent call last):
  File "pg.py", line 13, in <module>
    from filtered_eval import FilteredRankingEvaluator
ModuleNotFoundError: No module named 'filtered_eval'  
```

```
pip install torchbiggraph
Requirement already satisfied: torchbiggraph in ./.local/lib/python3.6/site-packages (1.dev0)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.6/site-packages (from torchbiggraph) (4.31.1)
Requirement already satisfied: torch>=1.0 in ./.local/lib/python3.6/site-packages (from torchbiggraph) (1.0.1.post2)
Requirement already satisfied: h5py in /opt/conda/lib/python3.6/site-packages (from torchbiggraph) (2.9.0)
Requirement already satisfied: attrs>=18.2.0 in /opt/conda/lib/python3.6/site-packages (from torchbiggraph) (19.1.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.6/site-packages (from torchbiggraph) (1.16.2)
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from h5py->torchbiggraph) (1.12.0)

**Comment by animesh** [comment]
`wget https://raw.githubusercontent.com/facebookresearch/PyTorch-BigGraph/master/examples/filtered_eval.py `
solves it, sorry for trouble!

**Comment by animesh** [comment]
```
$ git clone https://github.com/facebookresearch/PyTorch-BigGraph.git
cd PyTorch-BigGraph

```


to circumvent following error 
```
Traceback (most recent call last):
  File "pg.py", line 83, in <module>
    main()
  File "pg.py", line 58, in main
    rel_col=1,
  File "/home/ash022/.local/lib/python3.6/site-packages/torchbiggraph/converters/import_from_tsv.py", line 233, in convert_input_data
    validate_config(config)
  File "/home/ash022/.local/lib/python3.6/site-packages/torchbiggraph/converters/import_from_tsv.py", line 304, in validate_config
    user_config = get_config_dict_from_module(config)
  File "/home/ash022/.local/lib/python3.6/site-packages/torchbiggraph/config.py", line 394, in get_config_dict_from_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'examples/configs/fb15k_config.py'
```

**Comment by lerks** [comment]
Yes, as you guessed the example is not self-contained and needs a few more files to work. It's best to run it from a full checkout of the repo. We should probably clarify this...
