### ISSUE TITLE
[IndexError] with using custom data !

### ISSUE THREAD

**Issue by laifi** [facebookresearch/PyTorch-BigGraph#57]
I am really excited to try your promising software .
I created a data file composed of (linkedin_profile ids,relations,informations)

> relation  such as : skilled_in,interested_in,works_in...
> profile information such as : (skills,company,interests ....)

i used the same config file of the fb15k data ( i have already checked the config file and it looks like nothing to change for my data  )
So , i just runned this command : 
`!torchbiggraph_import_from_tsv \
  --lhs-col=0 --rel-col=1 --rhs-col=2 \
  PyTorch-BigGraph/torchbiggraph/examples/configs/fb15k_config.py \
  mydatafile.txt`

But , i got this error:

```
Looking up relation types in the edge files...
- Found 3 relation types
- Removing the ones with fewer than 1 occurrences...
- Left with 3 relation types
- Shuffling them...
Searching for the entities in the edge files...
Traceback (most recent call last):
  File "/usr/local/bin/torchbiggraph_import_from_tsv", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/converters/import_from_tsv.py", line 363, in main
    opt.relation_type_min_count,
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/converters/import_from_tsv.py", line 275, in convert_input_data
    entity_min_count,
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/converters/import_from_tsv.py", line 95, in collect_entities_by_type
    counters[relation_configs[rel_id].rhs][words[rhs_col]] += 1
IndexError: list index out of range
```

i runned this again but with only the first 100 lines of my data file, 
and it works this time ! What happened :question:  

**Thank You  !**

**Comment by lerks** [comment]
The most likely explanation is that your file is malformed and on one line you have only two columns rather than the three columns that are expected by the tool. We should probably update the tool to catch this type of errors and give a more actionable error message.

However, to get unblocked now, you can either manually inspect `mydatafile.txt` (or the code you used to generate it, in case) to see where it may be wrong or you can try to find what is the first line that is causing the tool to fail by doing a "binary search" on the number of lines. What I mean by that is: you know it works for the first 100 lines, you know it doesn't work for the entirety of the file which, let's suppose, is 1000 lines long. You can try running the tool on the first 550 lines of the file (which is 100 + 1000 / 2) and see if it works there. If it doesn't, then the problematic line is between 100 and 550, if it does work then the bad line is between 550 and 1000. You can repeat this process until you find the exact line. (Note that after you find the first line that causes issues and fix it, there may be other lines like it so you may have to run this whole thing again).

In general, as issue like this may mean that there's some problem in how you are generating the data that may be worth investigating. My best guess is that this is due to an incorrect handling of whitespace. Our tools splits a line into columns on _any_ sequence of whitespace characters, regardless of escaping or quotes. So if any of your entities has a name that contains a whitespace this will cause problems.

**Comment by lerks** [comment]
This issue was automatically closed because I pushed a commit that gives a clearer error message containing the line where the problem was encountered. If you now install PBG from the master branch it should be easier for you to debug the problem. Feel free to reopen this issue if you're still having problems.

**Comment by laifi** [comment]
@lerks Thank you so much for you support :smile:
